In [1]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats
import random
import warnings
warnings.filterwarnings('ignore')

In [2]:
x = np.arange(10, 20)
y = np.array([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])
z = np.array([5, 3, 2, 1, 0, -2, -8, -11, -15, -16])

print('Array x ranking: ', scipy.stats.rankdata(x))
print('Array y ranking: ', scipy.stats.rankdata(y))
print('Array z ranking: ', scipy.stats.rankdata(z))

Array x ranking:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Array y ranking:  [ 2.  1.  3.  4.  5.  6.  7.  8. 10.  9.]
Array z ranking:  [10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [3]:
scipy.stats.rankdata([8, 2, 0, 2])

array([4. , 2.5, 1. , 2.5])

In [4]:
scipy.stats.rankdata([8, 2, 0, 2], method='min')

array([4, 2, 1, 2], dtype=int64)

In [5]:
scipy.stats.rankdata([8, 2, 0, 2], method='max')

array([4, 3, 1, 3], dtype=int64)

In [6]:
scipy.stats.rankdata([8, np.nan, 0, 2])

array([nan, nan, nan, nan])

In [7]:
np.argsort(y)+1

array([ 2,  1,  3,  4,  5,  6,  7,  8, 10,  9], dtype=int64)

In [8]:
scipy.stats.spearmanr(x, y)

SignificanceResult(statistic=0.9757575757575757, pvalue=1.4675461874042197e-06)

In [9]:
rho, p = scipy.stats.spearmanr(x, y)
rho, p

(0.9757575757575757, 1.4675461874042197e-06)

In [10]:
xy = np.array([list(x),
               list(y)])

rho, p = scipy.stats.spearmanr(xy, axis=1)
rho, p

(0.9757575757575757, 1.4675461874042197e-06)

In [11]:
xyz = np.array([list(x),
                list(y),
                list(z)])

corr_matrix, p_matrix = scipy.stats.spearmanr(xyz, axis=1)
corr_matrix, p_matrix

(array([[ 1.        ,  0.97575758, -1.        ],
        [ 0.97575758,  1.        , -0.97575758],
        [-1.        , -0.97575758,  1.        ]]),
 array([[6.64689742e-64, 1.46754619e-06, 6.64689742e-64],
        [1.46754619e-06, 6.64689742e-64, 1.46754619e-06],
        [6.64689742e-64, 1.46754619e-06, 6.64689742e-64]]))

In [12]:
result = scipy.stats.kendalltau(x, y)
result

SignificanceResult(statistic=0.911111111111111, pvalue=2.9761904761904762e-05)

In [13]:
tau, p = scipy.stats.kendalltau(x, y)
tau, p

(0.911111111111111, 2.9761904761904762e-05)

In [14]:
x, y, z = pd.Series(x), pd.Series(y), pd.Series(z)
xy = pd.DataFrame({'x': x, 'y': y})
xyz = pd.DataFrame({'x': x, 'y': y, 'z': z})
xyz

x   y   z
0  10   2   5
1  11   1   3
2  12   4   2
3  13   5   1
4  14   8   0
5  15  12  -2
6  16  18  -8
7  17  25 -11
8  18  96 -15
9  19  48 -16

In [15]:
x.corr(y, method='spearman')

0.9757575757575757

In [16]:
xy.corr(method='spearman')

x         y
x  1.000000  0.975758
y  0.975758  1.000000

In [17]:
xyz.corr(method='spearman')

x         y         z
x  1.000000  0.975758 -1.000000
y  0.975758  1.000000 -0.975758
z -1.000000 -0.975758  1.000000

In [18]:
xy.corrwith(z, method='spearman')

x   -1.000000
y   -0.975758
dtype: float64

In [19]:
x.corr(y, method='kendall')

0.911111111111111

In [20]:
xy.corr(method='kendall')

x         y
x  1.000000  0.911111
y  0.911111  1.000000

In [21]:
xy.corrwith(z, method='kendall')

x   -1.000000
y   -0.911111
dtype: float64