In [1]:
import numpy as np

## Understanding NumPy Arrays

In [2]:
# Creating a NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


## Array Operations

In [3]:
# Basic operations
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_add = arr1 + arr2

# Multiplication
result_mul = arr1 * arr2
print("Addition Result:", result_add)
print("Multiplication Result:", result_mul)

Addition Result: [5 7 9]
Multiplication Result: [ 4 10 18]


## Array Indexing and Slicing

In [4]:
# Indexing and slicing
arr = np.array([0, 1, 2, 3, 4, 5])

# Accessing element at index 2
element_at_index_2 = arr[2]

# Slicing from index 1 to 4
slice_1_to_4 = arr[1:5]
print("Element at Index 2:", element_at_index_2)
print("Slice from 1 to 4:", slice_1_to_4)

Element at Index 2: 2
Slice from 1 to 4: [1 2 3 4]


## Shape and Reshaping

In [5]:
# Shape and reshaping
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Get shape
array_shape = arr.shape

# Reshape from 2x3 to 3x2
reshaped_arr = arr.reshape(3, 2)
print("Original Array Shape:", array_shape)
print("Reshaped Array:", reshaped_arr)

Original Array Shape: (2, 3)
Reshaped Array: [[1 2]
 [3 4]
 [5 6]]


## Mathematical Functions

In [6]:
# Mathematical functions
arr = np.array([1, 2, 3, 4, 5])

# Mean
mean_value = np.mean(arr)

# Standard deviation
std_deviation = np.std(arr)
print("Mean:", mean_value)
print("Standard Deviation:", std_deviation)

Mean: 3.0
Standard Deviation: 1.4142135623730951


## Random Module in NumPy

In [7]:
# Random module
random_numbers = np.random.rand(3, 3)  # 3x3 array of random numbers between 0 and 1

print("Random Numbers:", random_numbers)

Random Numbers: [[7.00717841e-01 5.00647765e-01 5.30921093e-01]
 [5.53058841e-04 4.29443038e-01 5.04756297e-01]
 [7.64556137e-01 3.63761551e-01 4.42210601e-01]]
