In [1]:
import numpy as np

## Creating NumPy Arrays

In [2]:
# defining a list of string elements
list_string = ['Audi', 'Tesla', 'Toyota', 'Mercedes', 'Ford']

# defining a list of numbers
list_number = [5, 4, 6, 7, 3]

# connverting the list list_string to a NumPy array
arr_str = np.array(list_string)

# connverting the list list_number to a NumPy array
arr_num = np.array(list_number)

In [3]:
# we simply define lists in np.array function
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix) #which will return 3x3 matrix

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [4]:
arr_1  = np.arange(start = 0, stop = 10) 
# which will create [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# or without mentioning start & stop keywords
arr_1  = np.arange(0,10)


# adding a step size
arr_step  = np.arange(start = 0, stop = 20, step = 5) 
# which will create [0, 5, 10, 15]

In [5]:
matrix_even = np.linspace(0,5)
matrix_even

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [6]:
matrix_zeros = np.zeros([3,5])
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
matrix_ones = np.ones([3,5])
matrix_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
matrix_eye = np.eye(5)
matrix_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## NumPy Functions