In [1]:
import numpy as np

## Creating NumPy Arrays

In [2]:
# defining a list of string elements
list_string = ['Audi', 'Tesla', 'Toyota', 'Mercedes', 'Ford']

# defining a list of numbers
list_number = [5, 4, 6, 7, 3]

# connverting the list list_string to a NumPy array
arr_str = np.array(list_string)

# connverting the list list_number to a NumPy array
arr_num = np.array(list_number)

In [3]:
# we simply define lists in np.array function
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix) #which will return 3x3 matrix

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [4]:
arr_1  = np.arange(start = 0, stop = 10) 
# which will create [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# or without mentioning start & stop keywords
arr_1  = np.arange(0,10)


# adding a step size
arr_step  = np.arange(start = 0, stop = 20, step = 5) 
# which will create [0, 5, 10, 15]

In [5]:
matrix_even = np.linspace(0,5)
matrix_even

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [6]:
matrix_zeros = np.zeros([3,5])
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
matrix_ones = np.ones([3,5])
matrix_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
matrix_eye = np.eye(5)
matrix_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## NumPy Functions

In [9]:
# defining an array with values 0 to 9
arr_10 = np.arange(0,10)
arr_re10 = arr_10.reshape([10,1])
arr_re10

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))

Sine Function: -0.7568024953079282
Cosine Function: -0.6536436208636119
Tan Function 1.1578212823495777


In [11]:
arr_exp = np.array([2,4,6])
np.exp(arr_exp)

# by default NumPy takes the base of log as e
np.log(2)
# log with base 10
np.log10(8)

0.9030899869919435

In [12]:
# we can +-*/ arrays together
# defining two arrays
arr_arc1 = np.arange(1,6)# -->[1, 2, 3, 4, 5]
arr_arc2 = np.arange(3,8)# -->[3, 4, 5, 6, 7]

print('Addition: ',arr_arc1+arr_arc2)
print('Subtraction: ',arr_arc2-arr_arc1)
print('Multiplication:' , arr_arc1*arr_arc2)
print('Division:', arr_arc1/arr_arc2)
print('Inverse:', 1/arr_arc1)
print('Powers:', arr_arc1**arr_arc2) # in python, powers are achieved using **, NOT ^!!! ^ does something completely different!

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication: [ 3  8 15 24 35]
Division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1    16   243  4096 78125]


In [13]:
# defining two matrices
matrix_op1 = np.arange(1,10).reshape(3,3)
matrix_op2 = np.eye(3)

print('Addition: \n', matrix_op1+matrix_op2)
print('Subtraction: \n ', matrix_op1-matrix_op2)
print('Multiplication: \n', matrix_op1*matrix_op2) # elementwise multiplication
print('Division: \n', matrix_op1/matrix_op2)
print('Multiplication: \n', matrix_op1 @ matrix_op2) # dot product

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
Multiplication: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


C:\Users\Wonyoung\AppData\Local\Temp\ipykernel_4460\3608463181.py:8: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix_op1/matrix_op2)


In [14]:
matrix_tr=np.arange(1,10).reshape(3,3) 
# --> [[1, 2, 3],[4, 5, 6],[7, 8, 9]] 3x3 matrix
np.transpose(matrix_tr)
# another way of taking a transpose matrix_tr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
print('Minimum value: ',np.min(matrix_tr))
print('Maximum value: ',np.max(matrix_tr))

Minimum value:  1
Maximum value:  9


In [16]:
rand_mat = np.random.rand(5,5) # uniform random variable
rand_mat

array([[0.52622468, 0.28651119, 0.03740352, 0.04405535, 0.3507095 ],
       [0.08434772, 0.15670276, 0.46154474, 0.22375218, 0.81703765],
       [0.80440146, 0.49586876, 0.43868802, 0.81963831, 0.17352923],
       [0.42575117, 0.62912676, 0.06090198, 0.53059988, 0.10251374],
       [0.08439061, 0.77370813, 0.17698181, 0.47973903, 0.03932429]])

In [17]:
rand_mat_2 = np.random.randn(500,500)
rand_mat_2

array([[-9.66456300e-02, -4.73027988e-01,  3.44072820e-01, ...,
        -9.19772977e-01, -6.20730281e-01,  1.39172245e+00],
       [ 1.50370403e-01,  9.87582846e-01, -9.20992774e-01, ...,
        -2.74841849e-01,  1.41867437e-01,  1.37292012e-01],
       [ 2.30660942e-01, -1.21886740e+00,  1.21736142e-03, ...,
         1.22587165e+00,  1.98072093e+00, -1.52232512e+00],
       ...,
       [ 1.81308602e-01,  1.22200861e+00, -2.18603875e-01, ...,
         3.23446272e-01,  6.74161959e-01,  5.52989327e-01],
       [ 8.60041124e-01,  6.66228070e-01,  6.99038617e-01, ...,
        -8.12598145e-01, -1.09572549e+00, -1.56818894e-01],
       [ 8.80150479e-01,  3.69810842e-01, -9.50439175e-01, ...,
         5.71044145e-01,  7.61362882e-01,  1.14922698e+00]])

In [18]:
print('Mean:',np.mean(rand_mat_2))
print('Standard Deviation:',np.std(rand_mat_2))

Mean: -0.00488605611755167
Standard Deviation: 1.0033159251547654


In [19]:
# Generating random values in an array
rand_mat3 = np.random.randint(1,5,10)
rand_mat3

array([3, 3, 1, 4, 1, 4, 1, 4, 2, 2])

## Accessing the entries of a Numpy Array

In [20]:
array_ac = np.array([3, 2, 1, 7, 4])

# accessing the 4 th entry of rand_arr
print(array_ac[3])

7


In [21]:
print(array_ac[2:4])

[1 7]


In [22]:
print(array_ac[[0, 3, 4]]) # accessing index 0, 3 & 4

[3 7 4]


In [23]:
# let's generate an array with 10 random values
rand_mat = np.random.randn(5,5)
rand_mat

array([[ 0.94305859,  1.10709709,  1.54186682,  0.58168784, -0.00928739],
       [-0.35275605,  0.48512258, -0.00734122, -0.09359177,  0.10067177],
       [-0.93281915, -1.42859984,  1.5595822 , -0.27516615,  1.27362736],
       [-0.67833822, -0.29879283,  2.48722318, -1.46886326,  1.06741164],
       [ 0.77254251, -0.56158006, -1.48452772, -0.93021557,  1.33553529]])

In [24]:
rand_mat[1]

array([-0.35275605,  0.48512258, -0.00734122, -0.09359177,  0.10067177])

In [25]:
# acessing third element of the second row
print(rand_mat[1][2])
#or
print(rand_mat[1,2])

-0.007341215604933153
-0.007341215604933153


In [26]:
print(rand_mat[0:2,1:3])

[[ 1.10709709  1.54186682]
 [ 0.48512258 -0.00734122]]


## Modifying entries of arrays

In [27]:
rand_mat[0:2,1:3] = [[1, 2],[3, 4]]
rand_mat

array([[ 0.94305859,  1.        ,  2.        ,  0.58168784, -0.00928739],
       [-0.35275605,  3.        ,  4.        , -0.09359177,  0.10067177],
       [-0.93281915, -1.42859984,  1.5595822 , -0.27516615,  1.27362736],
       [-0.67833822, -0.29879283,  2.48722318, -1.46886326,  1.06741164],
       [ 0.77254251, -0.56158006, -1.48452772, -0.93021557,  1.33553529]])

In [28]:
rand_mat[rand_mat<0]=0
rand_mat

array([[0.94305859, 1.        , 2.        , 0.58168784, 0.        ],
       [0.        , 3.        , 4.        , 0.        , 0.10067177],
       [0.        , 0.        , 1.5595822 , 0.        , 1.27362736],
       [0.        , 0.        , 2.48722318, 0.        , 1.06741164],
       [0.77254251, 0.        , 0.        , 0.        , 1.33553529]])

In [29]:
sub_mat=rand_mat[0:2,0:3]
print(sub_mat)

sub_mat=-1
print(rand_mat)

[[0.94305859 1.         2.        ]
 [0.         3.         4.        ]]
[[0.94305859 1.         2.         0.58168784 0.        ]
 [0.         3.         4.         0.         0.10067177]
 [0.         0.         1.5595822  0.         1.27362736]
 [0.         0.         2.48722318 0.         1.06741164]
 [0.77254251 0.         0.         0.         1.33553529]]


In [30]:
sub_mat = rand_mat[0:2,0:3].copy()
sub_mat

array([[0.94305859, 1.        , 2.        ],
       [0.        , 3.        , 4.        ]])