In [1]:
import numpy as np
import random

In [2]:
# Create an array
numbers = np.zeros((10,4))
for i in range(10):
    for j in range(4):
        numbers[i][j] = random.randint(1000,40000)

print(numbers)

[[ 7539. 17396. 24350. 34913.]
 [ 7388. 39053. 26418. 30030.]
 [15691.  6316.  2731.  8916.]
 [19186.  1332.  4400. 10215.]
 [ 7546. 29779. 39627. 22740.]
 [12080. 20099.  4360.  2483.]
 [27131. 34907.  8555. 14702.]
 [ 1465. 21649.  9683. 30193.]
 [15905. 28629. 33834.  7458.]
 [ 4558.  3400. 21145.  5668.]]


In [3]:
# Save
np.savetxt('data/save.txt', numbers, fmt='%d', delimiter=',')

In [4]:
# Load
a = np.loadtxt('data/save.txt', delimiter=',')
a

array([[ 7539., 17396., 24350., 34913.],
       [ 7388., 39053., 26418., 30030.],
       [15691.,  6316.,  2731.,  8916.],
       [19186.,  1332.,  4400., 10215.],
       [ 7546., 29779., 39627., 22740.],
       [12080., 20099.,  4360.,  2483.],
       [27131., 34907.,  8555., 14702.],
       [ 1465., 21649.,  9683., 30193.],
       [15905., 28629., 33834.,  7458.],
       [ 4558.,  3400., 21145.,  5668.]])

In [5]:
# Create an array
numbers = np.zeros((10,4))
for i in range(10):
    for j in range(4):
        numbers[i][j] = random.randint(1000,40000)
# Save as a .npy file
np.save('data/npy_test', arr=numbers)

In [6]:
# Read .npy file
npy_array = np.load(file='data/npy_test.npy')
npy_array[:5]

array([[35412., 36138., 22445.,  3885.],
       [38642., 14729., 34479., 11689.],
       [12069., 32741., 34702., 25260.],
       [ 3548.,  6168.,  8884.,  8584.],
       [26527., 17698., 32218.,  8333.]])