In [1]:
import numpy as np

## Creating NumPy Arrays

In [2]:
# defining a list of string elements
list_string = ['Audi', 'Tesla', 'Toyota', 'Mercedes', 'Ford']

# defining a list of numbers
list_number = [5, 4, 6, 7, 3]

# connverting the list list_string to a NumPy array
arr_str = np.array(list_string)

# connverting the list list_number to a NumPy array
arr_num = np.array(list_number)

In [3]:
# we simply define lists in np.array function
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix) #which will return 3x3 matrix

[[1 2 1]
 [4 5 9]
 [1 8 9]]


In [4]:
arr_1  = np.arange(start = 0, stop = 10) 
# which will create [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# or without mentioning start & stop keywords
arr_1  = np.arange(0,10)


# adding a step size
arr_step  = np.arange(start = 0, stop = 20, step = 5) 
# which will create [0, 5, 10, 15]

In [5]:
matrix_even = np.linspace(0,5)
matrix_even

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [6]:
matrix_zeros = np.zeros([3,5])
matrix_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
matrix_ones = np.ones([3,5])
matrix_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
matrix_eye = np.eye(5)
matrix_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## NumPy Functions

In [9]:
# defining an array with values 0 to 9
arr_10 = np.arange(0,10)
arr_re10 = arr_10.reshape([10,1])
arr_re10

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [10]:
print('Sine Function:',np.sin(4))
print('Cosine Function:',np.cos(4))
print('Tan Function',np.tan(4))

Sine Function: -0.7568024953079282
Cosine Function: -0.6536436208636119
Tan Function 1.1578212823495777


In [11]:
arr_exp = np.array([2,4,6])
np.exp(arr_exp)

# by default NumPy takes the base of log as e
np.log(2)
# log with base 10
np.log10(8)

0.9030899869919435

In [12]:
# we can +-*/ arrays together
# defining two arrays
arr_arc1 = np.arange(1,6)# -->[1, 2, 3, 4, 5]
arr_arc2 = np.arange(3,8)# -->[3, 4, 5, 6, 7]

print('Addition: ',arr_arc1+arr_arc2)
print('Subtraction: ',arr_arc2-arr_arc1)
print('Multiplication:' , arr_arc1*arr_arc2)
print('Division:', arr_arc1/arr_arc2)
print('Inverse:', 1/arr_arc1)
print('Powers:', arr_arc1**arr_arc2) # in python, powers are achieved using **, NOT ^!!! ^ does something completely different!

Addition:  [ 4  6  8 10 12]
Subtraction:  [2 2 2 2 2]
Multiplication: [ 3  8 15 24 35]
Division: [0.33333333 0.5        0.6        0.66666667 0.71428571]
Inverse: [1.         0.5        0.33333333 0.25       0.2       ]
Powers: [    1    16   243  4096 78125]


In [13]:
# defining two matrices
matrix_op1 = np.arange(1,10).reshape(3,3)
matrix_op2 = np.eye(3)

print('Addition: \n', matrix_op1+matrix_op2)
print('Subtraction: \n ', matrix_op1-matrix_op2)
print('Multiplication: \n', matrix_op1*matrix_op2) # elementwise multiplication
print('Division: \n', matrix_op1/matrix_op2)
print('Multiplication: \n', matrix_op1 @ matrix_op2) # dot product

Addition: 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Subtraction: 
  [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication: 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division: 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]
Multiplication: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


C:\Users\Wonyoung\AppData\Local\Temp\ipykernel_22932\3608463181.py:8: RuntimeWarning: divide by zero encountered in divide
  print('Division: \n', matrix_op1/matrix_op2)


In [14]:
matrix_tr=np.arange(1,10).reshape(3,3) 
# --> [[1, 2, 3],[4, 5, 6],[7, 8, 9]] 3x3 matrix
np.transpose(matrix_tr)
# another way of taking a transpose matrix_tr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [15]:
print('Minimum value: ',np.min(matrix_tr))
print('Maximum value: ',np.max(matrix_tr))

Minimum value:  1
Maximum value:  9


In [16]:
rand_mat = np.random.rand(5,5) # uniform random variable
rand_mat

array([[0.00135147, 0.41168379, 0.88848951, 0.93846478, 0.03948308],
       [0.81630239, 0.16211239, 0.66473382, 0.23556006, 0.11739569],
       [0.49805882, 0.41662388, 0.93021205, 0.73405794, 0.31888812],
       [0.82515322, 0.27919915, 0.52555963, 0.78813307, 0.04318048],
       [0.28942813, 0.46832655, 0.2516497 , 0.44997507, 0.60533621]])

In [17]:
rand_mat_2 = np.random.randn(500,500)
rand_mat_2

array([[ 1.27969454,  2.39434859,  1.15201916, ..., -0.7472936 ,
         0.89084222,  1.03930872],
       [ 0.38543153, -0.30632494,  0.35963438, ...,  0.76186673,
        -1.42322762,  0.52797098],
       [-1.19849512,  1.29179215, -0.65358034, ...,  1.43305024,
        -1.05990489, -0.65500126],
       ...,
       [ 1.35881031,  0.03422471,  0.88549893, ...,  0.90761758,
         0.25921146, -0.29195772],
       [ 1.28185713, -0.4351286 , -1.06573141, ..., -1.18228031,
         0.86599116,  1.68841994],
       [-0.02760709, -1.26923007, -0.26440855, ..., -0.14990736,
        -1.02579301,  1.3417045 ]])

In [18]:
print('Mean:',np.mean(rand_mat_2))
print('Standard Deviation:',np.std(rand_mat_2))

Mean: -0.002649694994274209
Standard Deviation: 0.9982665252463401


In [19]:
# Generating random values in an array
rand_mat3 = np.random.randint(1,5,10)
rand_mat3

array([2, 1, 4, 1, 2, 4, 1, 3, 3, 2])